name: The Schram Family
favicon: null
layout_spectrum: 0.8983687844593078
typography_spectrum: 0.9639431794639677
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.11089538014493883
  lightness: 0.4817070299759507
  saturation: 0.2211236886214465
  rhythmicContrast: 0.5707670475821942
purpose: []
